identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 40
  excluded:
    - dx
    - dy
    - dt
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - v
    - vm
    - id
overrides:
  - files:
      - "*Tests.swift"
    identifier_name:
      min_length:
        warning: 1
        error: 1
